### ISSUE TITLE
Did you preprocess the data during model training to remove howling occurrences? Is there a reference for howling data used in the training process?

### ISSUE THREAD

**Issue by Jojaeheung** [CARNIVAL-IITP/Acoustic_echo_cancellation#2]
Did you preprocess the data during model training to remove howling occurrences? Is there a reference for howling data used in the training process?

**Comment by wndvlf96** [comment]
Yes, I referred to a paper to generate howling with the dataset.

The paper's citation is as follows:

H. Gan, G. Luo, Y. Luo, W. Luo, "Howling Noise Cancellation in Time–Frequency Domain by Deep Neural Networks." In: Yang, XS., Sherratt, S., Dey, N., Joshi, A. (eds) Proceedings of Sixth International Congress on Information and Communication Technology. Lecture Notes in Networks and Systems, vol 236. Springer, Singapore, 2022.
