### ISSUE TITLE
Howling and echo can be eliminated together?

### ISSUE THREAD

**Issue by zuowanbushiwo** [CARNIVAL-IITP/Acoustic_echo_cancellation#6]
Hi @wndvlf96 @kimyungyeo 
     Can it do howling and echo cancellation at the same time? if  can't do both at the same time, who should do it first?
     How to download [SiTEC dataset](http://sitec.or.kr/)?  is it a open dataset?   When I visit this site, it always looks like this:
    ![image](https://user-images.githubusercontent.com/3354428/221148728-18821793-258b-4ec1-8a97-cf022801fa4b.png)
    thanks！

**Comment by wndvlf96** [comment]
Can it do howling and echo cancellation at the same time?
=> Although there are similarities between echo and howling, there have been studies that utilize individual algorithms to remove each issue or algorithms that remove howling using an echo removal algorithm. However, to our knowledge, there are no studies that have successfully removed both issues simultaneously. As part of our research, We are conducting research on cancelling echo and howling at the same time.

If can't do both at the same time, who should do it first?
=> There are attempts to eliminate howling with echo cancellation algorithms, given that the loudspeaker signal goes into the microphone for both echo and howling. So it may be suitable to apply the echo cancellation algorithm initially and subsequently apply the howling cancellation algorithm by removing residual echo or howling.

How to download SiTEC dataset (http://sitec.or.kr/)? is it a open dataset?
=> SiTEC is a paid dataset. Also the website can be accesed.

**Comment by zuowanbushiwo** [comment]
@wndvlf96
Thank you very much for your reply
> => Although there are similarities between echo and howling, there have been studies that utilize individual algorithms to remove each issue or algorithms that remove howling using an echo removal algorithm. However, to our knowledge, there are no studies that have successfully removed both issues simultaneously. As part of our research, We are conducting research on cancelling echo and howling at the same time.

so Is  HY_IITP_ESNet2 (A structure similar to conv-tasnet) for echo cancellation, and  is IITP_AFC  for eliminate residual echo , howling  and noise at the same time?  Is a LAEC ((Linear Acoustic Echo Cancellation, like NLMS, Kalman)required in front of HY_IITP_ESNet2?  How is the effect of this system? Do you have a demo ?
Thanks!

**Comment by wndvlf96** [comment]
HY_IITP_ESNet2 and IITP_AFC are individual modules used for echo cancellation and eliminating howling, respectively. In HY_IITP_ESNet2, LAEC is not required because it estimates a near-end signal directly from the mixture of the near-end and far-end signals. Although we do not have a demo currently, we will add one when it becomes available.

**Comment by zuowanbushiwo** [comment]
@wndvlf96 
Thank you very much for your reply,  I will keep an eye on your project . 
Is IITP_AFC just to eliminate the howling? Can't do noise and residual echo cancellation  together? I thought that the above three kinds of interference could be eliminated at the same time.
 And How to data  augmentation for howling,  I didn't find any datasets about howling,  Do you provide some preparation 
 scripts for howling data?
 Thanks！

**Comment by wndvlf96** [comment]
IITP_AFC is a individual module just for eliminating the howling.

Instead of preparation scripts for howling data, you may refer to resource "Howling Noise Cancellation in Time–Frequency Domain by Deep Neural Networks" to create a dataset about howling.
