### ISSUE TITLE
What is UEHC?

### ISSUE THREAD

**Issue by eingkim** [CARNIVAL-IITP/Acoustic_echo_cancellation#9]
What is UEHC? If it's Echo and Howling Cancellation, what kind of scenario should I think of?

**Comment by wndvlf96** [comment]
UEHC is the unified echo and howling cancellation.
Unlike the existing AEC system that receives the far-end speech signal, this scenario modeled an actual video conferencing environment that also considers the far-end system.
Thus, the near-end receives the estimated far-end speech siganl, and in the absence of a model, howling can occur.
